apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-ui-deployment
spec:
  selector:
    matchLabels:
      app: employee-ui
  template:
    metadata:
      labels:
        app: employee-ui
    spec:
      containers:
      - name: myapp
        image: prashantk123/employee-ui
        ports:
        - containerPort: 80
        imagePullPolicy: "Always"
      # tolerations:
      # - "key" : "CriticalAddonsOnly"
      #   "operator": "Equal"
      #   "value" : "true"
      #   "effect": "NoSchedule"