# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nginx-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: standard
#   volumeName: nginx-pvc