apiVersion: batch/v1
kind: Job
metadata:
  name: mssql-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: employee-db
        image: prashantk123/employee-db
      restartPolicy: Never